INSERT INTO STREET_NAME (name)
VALUES ('ul. 28 Lipca 1943'),
       ('ul. Abrahama'),
       ('ul. Adama Asnyka'),
       ('ul. Adama Chmiela'),
       ('ul. Adama Chmielowskiego'),
       ('ul. Adama Ciołkosza'),
       ('ul. Adama Habeli'),
       ('ul. Adama Krzyżanowskiego'),
       ('ul. Adama Marczyńskiego'),
       ('ul. Adama Prażmowskiego'),
       ('ul. Adama Próchnika'),
       ('ul. Adama Rysiewicza'),
       ('ul. Adama Staszczyka'),
       ('ul. Adolfa Aleksandrowicza'),
       ('ul. Adolfa Nowaczyńskiego'),
       ('ul. Adriana Baranieckiego'),
       ('ul. Agatowa'),
       ('ul. Agawy'),
       ('ul. Agrestowa'),
       ('ul. Akacjowa'),
       ('ul. Akademicka'),
       ('ul. Albańska'),
       ('ul. Albatrosów'),
       ('ul. Alberta Schweitzera'),
       ('ul. Aleja 29 Listopada'),
       ('ul. aleja 3 Maja'),
       ('ul. aleja Jana Pawła II'),
       ('ul. aleja Jerzego Waszyngtona'),
       ('ul. aleja Juliusza Słowackiego'),
       ('ul. aleja Jurajska'),
       ('ul. aleja Mieczysława Małeckiego'),
       ('ul. aleja Modrzewiowa'),
       ('ul. aleja Zygmunta Krasińskiego'),
       ('ul. Aleksandra Brücknera'),
       ('ul. Aleksandra Fredry'),
       ('ul. Aleksandra Gryglewskiego'),
       ('ul. Aleksandra Kotsisa'),
       ('ul. Aleksandra Krępy'),
       ('ul. Aleksandra Lubomirskiego'),
       ('ul. Aleksandra Orłowskiego'),
       ('ul. Aleksandra Prystora'),
       ('ul. Aleksandry'),
       ('ul. Alfreda Dauna'),
       ('ul. Algierska'),
       ('ul. Aliny'),
       ('ul. Alojzego Horaka'),
       ('ul. Alojzego Kaczmarczyka'),
       ('ul. Altanowa'),
       ('ul. Amarantowa'),
       ('ul. Amazonek'),
       ('ul. Ambrożego Grabowskiego'),
       ('ul. Andegaweńska'),
       ('ul. Andrieja Sacharowa'),
       ('ul. Andrychowska'),
       ('ul. Andrzeja Badurskiego'),
       ('ul. Andrzeja Frycza-Modrzewskiego'),
       ('ul. Andrzeja Małkowskiego'),
       ('ul. Andrzeja Michalika'),
       ('ul. Andrzeja Mycielskiego'),
       ('ul. Andrzeja Potebni'),
       ('ul. Andrzeja Sokołowskiego'),
       ('ul. Andrzeja Stopki'),
       ('ul. Anieli Krzywoń'),
       ('ul. Anny Jagiellonki'),
       ('ul. Anny Libera'),
       ('ul. Antoniego Augustynka-Wichury'),
       ('ul. Antoniego Dobrowolskiego'),
       ('ul. Antoniego Fertnera'),
       ('ul. Antoniego Gramatyka'),
       ('ul. Antoniego Hoborskiego'),
       ('ul. Antoniego Józefa Madalińskiego'),
       ('ul. Antoniego Kenara'),
       ('ul. Antoniego Kępińskiego'),
       ('ul. Antoniego Odyńca'),
       ('ul. Antoniego Pajdaka'),
       ('ul. Antyczna'),
       ('ul. Anusi'),
       ('ul. Architektów'),
       ('ul. Arcybiskupa Felińskiego'),
       ('ul. Ariańska'),
       ('ul. Arktyczna'),
       ('ul. Armii "Kraków"'),
       ('ul. Armii Krajowej'),
       ('ul. Artura Malawskiego'),
       ('ul. Astronautów'),
       ('ul. Astronomów'),
       ('ul. Augustiańska'),
       ('ul. Azaliowa'),
       ('ul. Babiego Lata'),
       ('ul. Babinicza'),
       ('ul. Bagatela'),
       ('ul. Bagienna'),
       ('ul. Bagrowa'),
       ('ul. Bajeczna'),
       ('ul. Balanówka'),
       ('ul. Balicka'),
       ('ul. Balladyny'),
       ('ul. Bałtycka'),
       ('ul. Barbary'),
       ('ul. Barbary Radziwiłłówny'),
       ('ul. Bardosa'),
       ('ul. Barska'),
       ('ul. Bartłomieja Groickiego'),
       ('ul. Bartłomieja Nowodworskiego'),
       ('ul. Bartnicza'),
       ('ul. Bartników'),
       ('ul. Bartosza'),
       ('ul. Bartosza Głowackiego'),
       ('ul. Barwinkowa'),
       ('ul. Barwna'),
       ('ul. Barycka'),
       ('ul. Bastionowa'),
       ('ul. Basztowa'),
       ('ul. Batalionów Chłopskich'),
       ('ul. Batalionu “Parasol”'),
       ('ul. Batalionu “Skała” AK'),
       ('ul. Batalionu “Zośka”'),
       ('ul. Batowicka'),
       ('ul. Bażancia'),
       ('ul. Bazarowa'),
       ('ul. Baziaka'),
       ('ul. Bednarska'),
       ('ul. Będzińska'),
       ('ul. Beera Meiselsa'),
       ('ul. Belwederczyków'),
       ('ul. Benedykta Cesarza'),
       ('ul. Benedykta Dybowskiego'),
       ('ul. Benedyktyńska'),
       ('ul. Berberysowa'),
       ('ul. Berdyczowska'),
       ('ul. Bernardyńska'),
       ('ul. Beskidzka'),
       ('ul. Betlejemska'),
       ('ul. Betonowa'),
       ('ul. Biała'),
       ('ul. Biała Droga'),
       ('ul. Białe Wzgórze'),
       ('ul. Białoprądnicka'),
       ('ul. Białoruska'),
       ('ul. Białostocka'),
       ('ul. Białych Brzóz'),
       ('ul. Bibicka'),
       ('ul. Bielańska'),
       ('ul. Bieńczycka'),
       ('ul. Bieńczycki Plac Targowy'),
       ('ul. Biernata z Lublina'),
       ('ul. Biesiadna'),
       ('ul. Bieszczadzka'),
       ('ul. Bieżanowska'),
       ('ul. Billewiczów'),
       ('ul. Biskupa Franciszka Hodura'),
       ('ul. Biskupa Jana Prandoty'),
       ('ul. Biskupa Józefa Gawliny'),
       ('ul. Biskupia'),
       ('ul. Biskupińska'),
       ('ul. Bławatkowa'),
       ('ul. Błażeja Czepca'),
       ('ul. Błękitna'),
       ('ul. Błotna'),
       ('ul. Błotniska'),
       ('ul. Bogumiła Pawłowskiego'),
       ('ul. Bolesława Czerwieńskiego'),
       ('ul. Bolesława Komorowskiego'),
       ('ul. Bolesława Kontryma'),
       ('ul. Bolesława Leśmiana'),
       ('ul. Bolesława Limanowskiego'),
       ('ul. Bolesława Prusa'),
       ('ul. Bolesława Śmiałego'),
       ('ul. Bór'),
       ('ul. Borowinowa'),
       ('ul. Bosacka'),
       ('ul. Bożego Ciała'),
       ('ul. Bożywoja'),
       ('ul. Braci Jamków'),
       ('ul. Braci Kiemliczów'),
       ('ul. Braci Polskich'),
       ('ul. Braci Schindlerów'),
       ('ul. Bracka'),
       ('ul. Branicka'),
       ('ul. Braterska'),
       ('ul. Braterstwa Broni'),
       ('ul. Bratkowa'),
       ('ul. Bratysławska'),
       ('ul. Brązownicza'),
       ('ul. Brogi'),
       ('ul. Bronisława Czecha'),
       ('ul. Bronisława Malinowskiego'),
       ('ul. Bronisława Pierackiego'),
       ('ul. Bronisława Schönborna'),
       ('ul. Bronowicka'),
       ('ul. Browarniana'),
       ('ul. Brunona Schulza'),
       ('ul. Bruśnicka'),
       ('ul. Bruzdowa'),
       ('ul. Brzask'),
       ('ul. Brzegowa'),
       ('ul. Brzeska'),
       ('ul. Brzozowa'),
       ('ul. Budrysów'),
       ('ul. Budziszyńska'),
       ('ul. Bugaj'),
       ('ul. Bukietowa'),
       ('ul. Bukowa'),
       ('ul. Bukszpanowa'),
       ('ul. Bularnia'),
       ('ul. Bułgarska'),
       ('ul. Bulwarowa'),
       ('ul. Buraczana'),
       ('ul. Burgundzka'),
       ('ul. Bursztynowa'),
       ('ul. Burzowa'),
       ('ul. Butrymów'),
       ('ul. Bystra'),
       ('ul. Bytomska'),
       ('ul. Cechowa'),
       ('ul. Cedrowa'),
       ('ul. Cedyńska'),
       ('ul. Ceglarska'),
       ('ul. Celarowska'),
       ('ul. Celna'),
       ('ul. Cementowa'),
       ('ul. Centkiewiczów'),
       ('ul. Centralna'),
       ('ul. Chabrowa'),
       ('ul. Chałubińskiego'),
       ('ul. Chęcińska'),
       ('ul. Chełmska'),
       ('ul. Chlebiczna'),
       ('ul. Chlebowa'),
       ('ul. Chłodna'),
       ('ul. Chłopska'),
       ('ul. Chmieleniec'),
       ('ul. Chmielna'),
       ('ul. Chmurna'),
       ('ul. Chochołowska'),
       ('ul. Chocimska'),
       ('ul. Chojnicka'),
       ('ul. Chopina'),
       ('ul. Chorzowska'),
       ('ul. Ciasna'),
       ('ul. Cicha'),
       ('ul. Cichociemnych AK'),
       ('ul. Cichy Kącik'),
       ('ul. Ciechanowska'),
       ('ul. Ciechocińska'),
       ('ul. Ciekowiec'),
       ('ul. Ciemna'),
       ('ul. Cienista'),
       ('ul. Ciepła'),
       ('ul. Ciepłownicza'),
       ('ul. Ciesielska'),
       ('ul. Cieszyńska'),
       ('ul. Cisowa'),
       ('ul. Combrowa'),
       ('ul. Cuplowa'),
       ('ul. Cygańska'),
       ('ul. Cypriana Godebskiego'),
       ('ul. Cypriana Kamila Norwida'),
       ('ul. Cyprysów'),
       ('ul. Cyryla Ratajskiego'),
       ('ul. Cystersów'),
       ('ul. Czajek'),
       ('ul. Czajna'),
       ('ul. Czapskich'),
       ('ul. Czarnogórska'),
       ('ul. Czarnowiejska'),
       ('ul. Czarodziejska'),
       ('ul. Czechosłowacka'),
       ('ul. Czeczeńska'),
       ('ul. Czeladnicza'),
       ('ul. Czeremchowa'),
       ('ul. Czereśniowa'),
       ('ul. Czerska'),
       ('ul. Czerwona'),
       ('ul. Czerwonego Kapturka'),
       ('ul. Czerwonego Prądnika'),
       ('ul. Czerwone Maki'),
       ('ul. Czesława Janczarskiego'),
       ('ul. Czesława Miłosza'),
       ('ul. Czesława Niemena'),
       ('ul. Czołgistów'),
       ('ul. Czorsztyńska'),
       ('ul. Czwartaków'),
       ('ul. Czysta'),
       ('ul. Czyżówka'),
       ('ul. Czyżyków'),
       ('ul. Czyżyńska'),
       ('ul. Dąbrowa'),
       ('ul. Dąbrówki'),
       ('ul. Dąbska'),
       ('ul. Dajwór'),
       ('ul. Daleka'),
       ('ul. Daliowa'),
       ('ul. Danalówka'),
       ('ul. Daniela Chodowieckiego'),
       ('ul. Danka'),
       ('ul. Danusi Jurandówny'),
       ('ul. Dębnicka'),
       ('ul. Dęboroga'),
       ('ul. Dębowa'),
       ('ul. Dekarzy'),
       ('ul. Dembowskiego'),
       ('ul. Deotymy'),
       ('ul. Dereniowa'),
       ('ul. Deszczowa'),
       ('ul. Dietla'),
       ('ul. Długa'),
       ('ul. Dobczycka'),
       ('ul. Dobiesława Kurozwęckiego'),
       ('ul. Dobra'),
       ('ul. Dobrego Pasterza'),
       ('ul. Doktora Jana Piltza'),
       ('ul. Doktora Józefa Babińskiego'),
       ('ul. Doktora Judyma'),
       ('ul. Doktora Owcy-Orwicza'),
       ('ul. Doktora Tadeusza Kudlińskiego'),
       ('ul. Dolina'),
       ('ul. Dolna'),
       ('ul. Dolnomłyńska'),
       ('ul. Dolnych Młynów'),
       ('ul. Dominikanów'),
       ('ul. Dominikańska'),
       ('ul. Domki'),
       ('ul. Domowa'),
       ('ul. Dożynkowa'),
       ('ul. Do Cegielni'),
       ('ul. Do Fortu'),
       ('ul. Do Luboni'),
       ('ul. Do Obserwatorium'),
       ('ul. Do Przystani'),
       ('ul. Do Sanktuarium Bożego Miłosierdzia'),
       ('ul. Do Wilgi'),
       ('ul. Do Wisły'),
       ('ul. Drewniana'),
       ('ul. droga Do Zamku'),
       ('ul. Droga nad Białuchą'),
       ('ul. Droga Rokadowa'),
       ('ul. Drożdżowa'),
       ('ul. Dróżka'),
       ('ul. Dróżnicka'),
       ('ul. Drożyna'),
       ('ul. Drożyska'),
       ('ul. Druhny Hanki'),
       ('ul. Drukarska'),
       ('ul. Druskiennicka'),
       ('ul. Drużbackiej'),
       ('ul. Duchacka'),
       ('ul. Dukatów'),
       ('ul. Duża Góra'),
       ('ul. Dworcowa'),
       ('ul. Dworna'),
       ('ul. Dworska'),
       ('ul. Dworski Ogród'),
       ('ul. Dymarek'),
       ('ul. Dymnik'),
       ('ul. Działkowa'),
       ('ul. Dziekanowicka'),
       ('ul. Dzielna'),
       ('ul. Dziewanny'),
       ('ul. Dziewiarzy'),
       ('ul. Dzikiej Róży'),
       ('ul. Edmunda Biernackiego'),
       ('ul. Edmunda Krzymuskiego'),
       ('ul. Edmunda Neussera'),
       ('ul. Edwarda Bzymka-Strzałkowskiego'),
       ('ul. Edwarda Heila'),
       ('ul. Edwarda Rydza-Śmigłego'),
       ('ul. Elizy Orzeszkowej'),
       ('ul. Elżbiety Łokietkówny'),
       ('ul. Emaus'),
       ('ul. Emila Dziedzica'),
       ('ul. Emila Godlewskiego'),
       ('ul. Emiliana Czyrniańskiego'),
       ('ul. Emilii Plater'),
       ('ul. Emilii Sczanieckiej'),
       ('ul. Erazma i Stanisława Fabijańskich'),
       ('ul. Erazma Jerzmanowskiego'),
       ('ul. Ernesta Cieślewskiego'),
       ('ul. Ernesta Solvaya'),
       ('ul. Estery'),
       ('ul. Estońska'),
       ('ul. Estreicherów'),
       ('ul. Eugeniusza Eibischa'),
       ('ul. Eugeniusza Kwiatkowskiego'),
       ('ul. Eugeniusza Romera'),
       ('ul. Fabryczna'),
       ('ul. Facimiech'),
       ('ul. Fałęcka'),
       ('ul. Falista'),
       ('ul. Falowa'),
       ('ul. Familijna'),
       ('ul. Farmaceutów'),
       ('ul. Fatimska'),
       ('ul. Felicjanek'),
       ('ul. Feliksa Jasieńskiego'),
       ('ul. Feliksa Konecznego'),
       ('ul. Feliksa Kopery'),
       ('ul. Feliksa Księżarskiego'),
       ('ul. Feliksa Radwańskiego'),
       ('ul. Feliksa Wrobela'),
       ('ul. Ferdynanda Kurasia'),
       ('ul. Filarecka'),
       ('ul. Filipa Eisenberga'),
       ('ul. Filipa Kallimacha'),
       ('ul. Filipa Pokutyńskiego'),
       ('ul. Filtrowa'),
       ('ul. Fiołkowa'),
       ('ul. Flisacka'),
       ('ul. Floriana Kotowskiego'),
       ('ul. Floriańska'),
       ('ul. Forteczna'),
       ('ul. Fosa'),
       ('ul. Franciszkańska'),
       ('ul. Franciszka Bielaka'),
       ('ul. Franciszka Bujaka'),
       ('ul. Franciszka Hynka'),
       ('ul. Franciszka Hypty'),
       ('ul. Franciszka Kajty'),
       ('ul. Franciszka Karpińskiego'),
       ('ul. Franciszka Kłaka'),
       ('ul. Franciszka Kniaźnina'),
       ('ul. Franciszka Kowalskiego'),
       ('ul. Franciszka Maryewskiego'),
       ('ul. Franciszka Niepokólczyckiego'),
       ('ul. Franciszka Pększyca-Grudzińskiego'),
       ('ul. Franciszka Ptaka'),
       ('ul. Franciszka Sapalskiego'),
       ('ul. Franciszka Stefczyka'),
       ('ul. Gabriela Narutowicza'),
       ('ul. Gacki'),
       ('ul. Gaik'),
       ('ul. Gajowa'),
       ('ul. Gajówka'),
       ('ul. Galaktyczna'),
       ('ul. Garbarska'),
       ('ul. Garncarska'),
       ('ul. Gazowa'),
       ('ul. Gdańska'),
       ('ul. Gdowska'),
       ('ul. Gdyńska'),
       ('ul. Gen. Leopolda Okulickiego'),
       ('ul. Generała Augusta Fieldorfa-Nila'),
       ('ul. Generała Bernarda Monda'),
       ('ul. Generała Bolesława Roi'),
       ('ul. Generała Franciszka Kleeberga'),
       ('ul. Generała Franciszka Paszkowskiego'),
       ('ul. Generała Ignacego Prądzyńskiego'),
       ('ul. Generała Jakuba Jasińskiego'),
       ('ul. Generała Jana Karcza'),
       ('ul. Generała Józefa Bema'),
       ('ul. Generała Józefa Chłopickiego'),
       ('ul. Generała Józefa Olszyny-Wilczyńskiego'),
       ('ul. Generała Juliana Filipowicza'),
       ('ul. Generała Kazimierza Sosnkowskiego'),
       ('ul. Generała Kiwerskiego'),
       ('ul. Generała Mariana Kukiela'),
       ('ul. Generała Michała Karaszewicza-Tokarzewskiego'),
       ('ul. Generała Romana Sołtyka'),
       ('ul. Generała Tadeusza Kutrzeby'),
       ('ul. Generała Tadeusza Pełczyńskiego'),
       ('ul. Geodetów'),
       ('ul. Geologów'),
       ('ul. Gerberowa'),
       ('ul. Gęsia'),
       ('ul. Gilowa'),
       ('ul. Gipsowa'),
       ('ul. Głębinowa'),
       ('ul. Głęboka'),
       ('ul. Gliniana'),
       ('ul. Glinik'),
       ('ul. Głogowa'),
       ('ul. Głogowiec'),
       ('ul. Głogowska'),
       ('ul. Gminna'),
       ('ul. Gnieźnieńska'),
       ('ul. Gołaśka'),
       ('ul. Gołębia'),
       ('ul. Gołębia ulica'),
       ('ul. Golikówka'),
       ('ul. Golkowicka'),
       ('ul. Gontyna'),
       ('ul. Goplana'),
       ('ul. Górna'),
       ('ul. Górników'),
       ('ul. Górska'),
       ('ul. Goryczkowa'),
       ('ul. Gościnna'),
       ('ul. Gospodarska'),
       ('ul. Goździkowa'),
       ('ul. Grabowa'),
       ('ul. Grabówki'),
       ('ul. Grąby'),
       ('ul. Gradowa'),
       ('ul. Graniczna'),
       ('ul. Granitowa'),
       ('ul. Grawerska'),
       ('ul. Grażyny'),
       ('ul. Grażyny Bacewiczówny'),
       ('ul. Grębałowska'),
       ('ul. Grenadierów'),
       ('ul. Grochowa'),
       ('ul. Grochowska'),
       ('ul. Grodzisko'),
       ('ul. Grodzka'),
       ('ul. Gromady Grudziąż'),
       ('ul. Gromadzka'),
       ('ul. Gronostajowa'),
       ('ul. Gronowa'),
       ('ul. Groszkowa'),
       ('ul. Grota-Roweckiego'),
       ('ul. Grunwaldzka'),
       ('ul. Gryczana'),
       ('ul. Grzegorza Korzeniaka'),
       ('ul. Grzegorza z Sanoka'),
       ('ul. Grzegórzecka'),
       ('ul. Grzybki'),
       ('ul. Gumniska'),
       ('ul. Gustawa Daniłowskiego'),
       ('ul. Gustawa Ehrenberga'),
       ('ul. Gustawa Herlinga-Grudzińskiego'),
       ('ul. Gustawa Morcinka'),
       ('ul. Gustawa Pokrzywki'),
       ('ul. Gwarecka'),
       ('ul. Gwarna'),
       ('ul. Gwieździsta'),
       ('ul. Gzymsików'),
       ('ul. Habina'),
       ('ul. Halicka'),
       ('ul. Haliny Cieślińskiej-Brzeskiej'),
       ('ul. Halki'),
       ('ul. Hamernia'),
       ('ul. Hanny Mortkowicz-Olczakowej'),
       ('ul. Hansa Christiana Andersena'),
       ('ul. Harcerska'),
       ('ul. Harcerzy Krakowskich'),
       ('ul. Harcmistrza Stanisława Millana'),
       ('ul. Harcmistrza Stanisława Orszy-Broniewskiego'),
       ('ul. Harnasiów'),
       ('ul. Hektary'),
       ('ul. Helclów'),
       ('ul. Heleny'),
       ('ul. Heleny Chanieckiej'),
       ('ul. Heleny i Leona Patynów'),
       ('ul. Heleny Marusarzówny'),
       ('ul. Heleny Modrzejewskiej'),
       ('ul. Heligundy'),
       ('ul. Henryka Barycza'),
       ('ul. Henryka Brodatego'),
       ('ul. Henryka Czeczotta'),
       ('ul. Henryka Flame'),
       ('ul. Henryka Hoyera'),
       ('ul. Henryka Kułakowskiego'),
       ('ul. Henryka Müncha'),
       ('ul. Henryka Niewodniczańskiego'),
       ('ul. Henryka Pachońskiego'),
       ('ul. Henryka Reymana'),
       ('ul. Henryka Rodakowskiego'),
       ('ul. Henryka Rowida'),
       ('ul. Henryka Siemiradzkiego'),
       ('ul. Henryka Sienkiewicza'),
       ('ul. Herbowa'),
       ('ul. Hetmańska'),
       ('ul. Hiacyntowa'),
       ('ul. Hieronima Pinocci'),
       ('ul. Hieronima Wietora'),
       ('ul. Hołdu Pruskiego'),
       ('ul. Hoża'),
       ('ul. Hubalczyków'),
       ('ul. Huculska'),
       ('ul. Hufcowa'),
       ('ul. Hugona Kołłątaja'),
       ('ul. Husarska'),
       ('ul. Ignacego Chrzanowskiego'),
       ('ul. Ignacego Domeyki'),
       ('ul. Ignacego Grabczaka'),
       ('ul. Ignacego Krasickiego'),
       ('ul. Ignacego Mościckiego'),
       ('ul. Ignacego Paderewskiego'),
       ('ul. Igołomska'),
       ('ul. Igrców'),
       ('ul. Iłowa'),
       ('ul. Imbramowska'),
       ('ul. Imielna'),
       ('ul. Inicjatywy Lokalnej'),
       ('ul. Insurekcji Kościuszkowskiej'),
       ('ul. Inżyniera Adama Bielańskiego'),
       ('ul. Ireny Kosmowskiej'),
       ('ul. Irysowa'),
       ('ul. Isep'),
       ('ul. Ivo Andricia'),
       ('ul. Iwona Odrowąża'),
       ('ul. Iwonicka'),
       ('ul. Izaaka'),
       ('ul. Izydora Kopernickiego'),
       ('ul. Izydora Stella-Sawickiego'),
       ('ul. Jabłonkowska'),
       ('ul. Jabłonna'),
       ('ul. Jabłonowskich'),
       ('ul. Jacka Jezierskiego'),
       ('ul. Jacka Kluszewskiego'),
       ('ul. Jacka Malczewskiego'),
       ('ul. Jadwigi Majówny'),
       ('ul. Jadwigi z Łobzowa'),
       ('ul. Jadźwingów'),
       ('ul. Jagiełka'),
       ('ul. Jagiellońska'),
       ('ul. Jagienki'),
       ('ul. Jaglana'),
       ('ul. Jagodowa'),
       ('ul. Jakuba'),
       ('ul. Jakuba Majora'),
       ('ul. Jałowcowa'),
       ('ul. Janasówka'),
       ('ul. Jana Aleksandra Gorczyna'),
       ('ul. Jana Brożka'),
       ('ul. Jana Brzechwy'),
       ('ul. Jana Bułhaka'),
       ('ul. Jana Buszka'),
       ('ul. Jana Chryzostoma Paska'),
       ('ul. Jana Dekerta'),
       ('ul. Jana Długosza'),
       ('ul. Jana Gajocha'),
       ('ul. Jana Grzecha'),
       ('ul. Jana Gumowskiego'),
       ('ul. Jana Gutenberga'),
       ('ul. Jana Hallera'),
       ('ul. Jana Henryka Dąbrowskiego'),
       ('ul. Jana Heweliusza'),
       ('ul. Jana Janowskiego'),
       ('ul. Jana Kaczary'),
       ('ul. Jana Kantego Andrusikiewicza'),
       ('ul. Jana Kantego Przyzby'),
       ('ul. Jana Kasprowicza'),
       ('ul. Jana Kazimierza'),
       ('ul. Jana Kiepury'),
       ('ul. Jana Kilińskiego'),
       ('ul. Jana Kluka'),
       ('ul. Jana Kochanowskiego'),
       ('ul. Jana Kozietulskiego'),
       ('ul. Jana Kremskiego'),
       ('ul. Jana Kurczaba'),
       ('ul. Jana Lechonia'),
       ('ul. Jana Maklakiewicza'),
       ('ul. Jana Miodońskiego'),
       ('ul. Jana Mosdorfa'),
       ('ul. Jana Muszyńskiego'),
       ('ul. Jana Nowaka'),
       ('ul. Jana Olbrachta'),
       ('ul. Jana Ostroroga'),
       ('ul. Jana Palacha'),
       ('ul. Jana Pawła II'),
       ('ul. Jana Pietrusińskiego'),
       ('ul. Jana Piwnika “Ponurego”'),
       ('ul. Jana Sabały'),
       ('ul. Jana Sas-Zubrzyckiego'),
       ('ul. Jana Skrzetuskiego'),
       ('ul. Jana Smolenia'),
       ('ul. Jana Sobieskiego'),
       ('ul. Jana Stanisława Bystronia'),
       ('ul. Jana Stanisławskiego'),
       ('ul. Jana Szwai'),
       ('ul. Jana XXIII'),
       ('ul. Jana Zygmunta Robla'),
       ('ul. Janiny Porazińskiej'),
       ('ul. Janka Szumca'),
       ('ul. Janosika'),
       ('ul. Janowa Wola'),
       ('ul. Jantarowa'),
       ('ul. Janusza Korczaka'),
       ('ul. Janusza Kusocińskiego'),
       ('ul. Janusza Meissnera'),
       ('ul. Jar'),
       ('ul. Jarosława Dolińskiego'),
       ('ul. Jarosława Iwaszkiewicza'),
       ('ul. Jarosławska'),
       ('ul. Jarzębiny'),
       ('ul. Jarzynowa'),
       ('ul. Jasełkowa'),
       ('ul. Jasia i Małgosi'),
       ('ul. Jasielska'),
       ('ul. Jaskółcza'),
       ('ul. Jaskrowa'),
       ('ul. Jaśminowa'),
       ('ul. Jasna'),
       ('ul. Jasnogórska'),
       ('ul. Jastrzębia'),
       ('ul. Jaworowa'),
       ('ul. Jaxy Gryfity'),
       ('ul. Jazowa'),
       ('ul. Jęczmienna'),
       ('ul. Jeleniogórska'),
       ('ul. Jeleniowa'),
       ('ul. Jemiołowa'),
       ('ul. Jemiołuszek'),
       ('ul. Jerozolimska'),
       ('ul. Jerzego Bajana'),
       ('ul. Jerzego Dobrzyckiego'),
       ('ul. Jerzego Fedkowicza'),
       ('ul. Jerzego Giedroycia'),
       ('ul. Jerzego Harasymowicza'),
       ('ul. Jerzego Jurowicza'),
       ('ul. Jerzego Korohody'),
       ('ul. Jerzego Kuryłowicza'),
       ('ul. Jerzego Lande'),
       ('ul. Jerzego Potrzebowskiego'),
       ('ul. Jerzego Samuela Bandtkiego'),
       ('ul. Jerzego Smoleńskiego'),
       ('ul. Jesienna'),
       ('ul. Jesionowa'),
       ('ul. Jeździecka'),
       ('ul. Jeziorany'),
       ('ul. Jeziorko'),
       ('ul. Jeżów'),
       ('ul. Jezuitów'),
       ('ul. Jeżynowa'),
       ('ul. Jodłowa'),
       ('ul. Jontkowa Górka'),
       ('ul. Jordanowska'),
       ('ul. Joselewicza'),
       ('ul. Josepha Conrada'),
       ('ul. Józefa'),
       ('ul. Józefa Becka'),
       ('ul. Józefa Bellerta'),
       ('ul. Józefa Brodowicza'),
       ('ul. Józefa Chełmońskiego'),
       ('ul. Józefa Chełmońskiego-Deptak'),
       ('ul. Józefa Czajkowskiego'),
       ('ul. Józefa Dwernickiego'),
       ('ul. Józefa Elsnera'),
       ('ul. Józefa Friedleina'),
       ('ul. Józefa Gałęzowskiego'),
       ('ul. Józefa Herzoga'),
       ('ul. Józefa i Agaty Gwizdałów'),
       ('ul. Józefa i Floriana Sawiczewskich'),
       ('ul. Józefa Korzeniowskiego'),
       ('ul. Józefa Kostrzewskiego'),
       ('ul. Józefa Krasnowolskiego'),
       ('ul. Józefa Kraszewskiego'),
       ('ul. Józefa Kustronia'),
       ('ul. Józefa Mackiewicza'),
       ('ul. Józefa Marcika'),
       ('ul. Józefa Mehoffera'),
       ('ul. Józefa Montwiłła-Mireckiego'),
       ('ul. Józefa Morozewicza'),
       ('ul. Józefa Narzymskiego'),
       ('ul. Józefa Ostafina'),
       ('ul. Józefa Pankiewicza'),
       ('ul. Józefa Piłsudskiego'),
       ('ul. Józefa Rostafińskiego'),
       ('ul. Józefa Rzebika'),
       ('ul. Józefa Sarego'),
       ('ul. Józefa Sawy-Calińskiego'),
       ('ul. Józefa Sowińskiego'),
       ('ul. Józefa Szujskiego'),
       ('ul. Józefińska'),
       ('ul. Józefitów'),
       ('ul. Jubileuszowa'),
       ('ul. Jugowicka'),
       ('ul. Juliana Dunajewskiego'),
       ('ul. Juliana Fałata'),
       ('ul. Juliana Goslara'),
       ('ul. Juliana Konstantego Ordona'),
       ('ul. Juliana Przybosia'),
       ('ul. Juliana Ursyna Niemcewicza'),
       ('ul. Julii Nenko'),
       ('ul. Juliusza Kadena-Bandrowskiego'),
       ('ul. Juliusza Kleinera'),
       ('ul. Juliusza Lea'),
       ('ul. Juliusza Osterwy'),
       ('ul. Junacka'),
       ('ul. Jurajska'),
       ('ul. Juranda ze Spychowa'),
       ('ul. Jurka Bitschana'),
       ('ul. Justowska'),
       ('ul. Jutrzenka'),
       ('ul. Jutrzyńska'),
       ('ul. Kącik'),
       ('ul. Kacza'),
       ('ul. Kaczeńcowa'),
       ('ul. Kaczorówka'),
       ('ul. Kadecka'),
       ('ul. Kadrówki'),
       ('ul. Kaimska'),
       ('ul. Kajetana Koźmiana'),
       ('ul. Kąkolowa'),
       ('ul. Kaktusowa'),
       ('ul. Kalinowa'),
       ('ul. Kaliska'),
       ('ul. Kalwaryjska'),
       ('ul. Kalwińska'),
       ('ul. Kamedulska'),
       ('ul. Kameliowa'),
       ('ul. Kamieniarska'),
       ('ul. Kamieniecka'),
       ('ul. Kamienna'),
       ('ul. Kamieńskiego'),
       ('ul. Kamionka'),
       ('ul. Kanarkowa'),
       ('ul. Kanonicza'),
       ('ul. Kanonierów'),
       ('ul. Kantorowicka'),
       ('ul. Kapelanka'),
       ('ul. Kąpielowa'),
       ('ul. Kapucyńska'),
       ('ul. Karasiówka'),
       ('ul. Karmelicka'),
       ('ul. Karola Bunscha'),
       ('ul. Karola Darwina'),
       ('ul. Karola Frycza'),
       ('ul. Karola Homolacsa'),
       ('ul. Karola Irzykowskiego'),
       ('ul. Karola i Jerzego Drozdowskich'),
       ('ul. Karola Jana Chodkiewicza'),
       ('ul. Karola Kurpińskiego'),
       ('ul. Karola Olszewskiego'),
       ('ul. Karola Popiela'),
       ('ul. Karola Rollego'),
       ('ul. Karowa'),
       ('ul. Karpacka'),
       ('ul. Kaspra Bażanki'),
       ('ul. Kasztelańska'),
       ('ul. Kaszubska'),
       ('ul. Kąt'),
       ('ul. Kątowa'),
       ('ul. Katowicka'),
       ('ul. Kawiory'),
       ('ul. Kawowa'),
       ('ul. Kazimierza Brodzińskiego'),
       ('ul. Kazimierza Chałupnika'),
       ('ul. Kazimierza Czapińskiego'),
       ('ul. Kazimierza Herwina-Piątka'),
       ('ul. Kazimierza Jagiellończyka'),
       ('ul. Kazimierza Kierzkowskiego'),
       ('ul. Kazimierza Kordylewskiego'),
       ('ul. Kazimierza Kostaneckiego'),
       ('ul. Kazimierza Morawskiego'),
       ('ul. Kazimierza Nitscha'),
       ('ul. Kazimierza Odnowiciela'),
       ('ul. Kazimierza Pluty-Czachowskiego'),
       ('ul. Kazimierza Pochwalskiego'),
       ('ul. Kazimierza Pułaskiego'),
       ('ul. Kazimierza Pużaka'),
       ('ul. Kazimierza Siemienowicza'),
       ('ul. Kazimierza Sprawiedliwego'),
       ('ul. Kazimierza Wielkiego'),
       ('ul. Kędzierzyńska'),
       ('ul. Kępna'),
       ('ul. Kępska'),
       ('ul. Ketlinga'),
       ('ul. Kielecka'),
       ('ul. Kijanki'),
       ('ul. Klasztorna'),
       ('ul. Klemensa Bąkowskiego'),
       ('ul. Klemensa Janickiego'),
       ('ul. Klemensa z Ruszczy'),
       ('ul. Klementyny Hoffmanowej'),
       ('ul. Klimka Bachledy'),
       ('ul. Kliniec'),
       ('ul. Klonowa'),
       ('ul. Kłosowa'),
       ('ul. Kluczborska'),
       ('ul. Kłuszyńska'),
       ('ul. Kmicica'),
       ('ul. Kmieca'),
       ('ul. Kminkowa'),
       ('ul. Kobierzyńska'),
       ('ul. Kocmyrzowska'),
       ('ul. Kogucia'),
       ('ul. Kokosowa'),
       ('ul. Kokotowska'),
       ('ul. Kołaczy'),
       ('ul. Kolarzy'),
       ('ul. Kolędnicza'),
       ('ul. Kolejarzy'),
       ('ul. Kolejowa'),
       ('ul. Koletek'),
       ('ul. Kolista'),
       ('ul. Kolna'),
       ('ul. Kołobrzeska'),
       ('ul. Kołodziejska'),
       ('ul. Kolonijna'),
       ('ul. Kołowa'),
       ('ul. Koło Białuchy'),
       ('ul. Koło Strzelnicy'),
       ('ul. Komandosów'),
       ('ul. Komasy'),
       ('ul. Komuny Paryskiej'),
       ('ul. Konfederacka'),
       ('ul. Konopna'),
       ('ul. Konrada Srzednickiego'),
       ('ul. Konrada Wallenroda'),
       ('ul. Konstantego Brandla'),
       ('ul. Konstantego Ciołkowskiego'),
       ('ul. Konstantego Ildefonsa Gałczyńskiego'),
       ('ul. Konstantego Jelskiego'),
       ('ul. Konstantego Krumłowskiego'),
       ('ul. Konstantego Laszczki'),
       ('ul. Konwaliowa'),
       ('ul. Konwisarzy'),
       ('ul. Kopalina'),
       ('ul. Kopaniec'),
       ('ul. Koprowa'),
       ('ul. Koralowa'),
       ('ul. Kordiana'),
       ('ul. Korepty'),
       ('ul. Kormoranów'),
       ('ul. Kornela Makuszyńskiego'),
       ('ul. Korony Polskiej'),
       ('ul. Kościelna'),
       ('ul. Kościelnicka'),
       ('ul. Kościuszkowców'),
       ('ul. Kosiarzy'),
       ('ul. Kosmonautów'),
       ('ul. Kosocicka'),
       ('ul. Kosów'),
       ('ul. Kostrzecka'),
       ('ul. Kosynierów'),
       ('ul. Koszalińska'),
       ('ul. Koszarówka'),
       ('ul. Koszutki'),
       ('ul. Koszykarska'),
       ('ul. Kotlarska'),
       ('ul. Kotówka'),
       ('ul. Kowalska'),
       ('ul. Kozia'),
       ('ul. Koziarówka'),
       ('ul. Kozienicka'),
       ('ul. Koźlarska'),
       ('ul. Krajobrazowa'),
       ('ul. Krakowska'),
       ('ul. Krakusa'),
       ('ul. Krakusów'),
       ('ul. Krańcowa'),
       ('ul. Krasowa'),
       ('ul. Krawiecka'),
       ('ul. Kremerowska'),
       ('ul. Kresowa'),
       ('ul. Kręta'),
       ('ul. Krochmalniki'),
       ('ul. Krokusowa'),
       ('ul. Króla Jana III Sobieskiego'),
       ('ul. Królewska'),
       ('ul. Królowej Bony'),
       ('ul. Królowej Jadwigi'),
       ('ul. Królowej Marysieńki'),
       ('ul. Królówka'),
       ('ul. Kronikarza Galla'),
       ('ul. Krośnieńska'),
       ('ul. Krótka'),
       ('ul. Krowoderska'),
       ('ul. Krowoderskich Zuchów'),
       ('ul. Krucza'),
       ('ul. Krupnicza'),
       ('ul. Kruszwicka'),
       ('ul. Krymska'),
       ('ul. Kryniczna'),
       ('ul. Krystyna z Ostrowa'),
       ('ul. Kryształowa'),
       ('ul. Krzemieniecka'),
       ('ul. Krzemionki'),
       ('ul. Krzesławicka'),
       ('ul. Krzewowa'),
       ('ul. Krzysztofa Kamila Baczyńskiego'),
       ('ul. Krzywa'),
       ('ul. Krzywda'),
       ('ul. Krzywy Zaułek'),
       ('ul. Krzyżówka'),
       ('ul. Krzyżtoporska'),
       ('ul. Ksawerego Pruszyńskiego'),
       ('ul. Księcia Józefa'),
       ('ul. Księdza Augustyna Kordeckiego'),
       ('ul. Księdza Kazimierza Siemaszki'),
       ('ul. Księdza Piotra Skargi'),
       ('ul. Księżnej Przybysławy'),
       ('ul. Księżycowa'),
       ('ul. Kujawska'),
       ('ul. Kukiełek Golkowickich'),
       ('ul. Kukułcza'),
       ('ul. Kupa'),
       ('ul. Kupały'),
       ('ul. Kurkowa'),
       ('ul. Kurniki'),
       ('ul. Kuśnierska'),
       ('ul. Kuźnicy Kołłątajowskiej'),
       ('ul. Kuźnicza'),
       ('ul. Ku Raciborowicom'),
       ('ul. Kwartowa'),
       ('ul. Kwatery'),
       ('ul. Kwiatowa'),
       ('ul. Kwiatów Polskich'),
       ('ul. Kwiecista'),
       ('ul. Kwietna'),
       ('ul. Lajkonika'),
       ('ul. Lanckorońska'),
       ('ul. Lasek'),
       ('ul. Laskowa'),
       ('ul. Lasogórska'),
       ('ul. Lasowisko'),
       ('ul. Lasówka'),
       ('ul. Laudańska'),
       ('ul. Lawendowa'),
       ('ul. Lazurowa'),
       ('ul. Lecha'),
       ('ul. Lechicka'),
       ('ul. Lecznicza'),
       ('ul. Legendy'),
       ('ul. Legionów'),
       ('ul. Legionów Józefa Piłsudskiego'),
       ('ul. Legnicka'),
       ('ul. Lekarska'),
       ('ul. Leona Chwistka'),
       ('ul. Leona Misiołka'),
       ('ul. Leona Wyczółkowskiego'),
       ('ul. Leopolda Flanka'),
       ('ul. Leopolda Kmietowicza'),
       ('ul. Leopolda Lisa-Kuli'),
       ('ul. Leopolda Staffa'),
       ('ul. Lesista'),
       ('ul. Leśna'),
       ('ul. Leszczynowa'),
       ('ul. Leszka Białego'),
       ('ul. Leszka Czarnego'),
       ('ul. Letnia'),
       ('ul. Lewkowa'),
       ('ul. Libertowska'),
       ('ul. Librowszczyzna'),
       ('ul. Liliowa'),
       ('ul. Lilli Wenedy'),
       ('ul. Lipowa'),
       ('ul. Lipska'),
       ('ul. Lirników'),
       ('ul. Liryczna'),
       ('ul. Liściasta'),
       ('ul. Lisia'),
       ('ul. Litawora'),
       ('ul. Litewska'),
       ('ul. Lniana'),
       ('ul. Łobzowska'),
       ('ul. Longinusa Podbipięty'),
       ('ul. Loretańska'),
       ('ul. Lotnicza'),
       ('ul. Lubelska'),
       ('ul. Lubicz'),
       ('ul. Lublańska'),
       ('ul. Lubocka'),
       ('ul. Lubostroń'),
       ('ul. Lubuska'),
       ('ul. Lucjana Rydla'),
       ('ul. Lucjana Siemieńskiego'),
       ('ul. Łuczanowicka'),
       ('ul. Ludmiły Korbutowej'),
       ('ul. Ludomiła Korczyńskiego'),
       ('ul. Ludomira Benedyktowicza'),
       ('ul. Ludomira Różyckiego'),
       ('ul. Ludowa'),
       ('ul. Ludwika Bierkowskiego'),
       ('ul. Ludwika Gardowskiego'),
       ('ul. Ludwika Hieronima Morstina'),
       ('ul. Ludwika Idzikowskiego'),
       ('ul. Ludwika Jędrzejczyka'),
       ('ul. Ludwika Krzywickiego'),
       ('ul. Ludwika Mierosławskiego'),
       ('ul. Ludwika Muzyczki'),
       ('ul. Ludwika Nabielaka'),
       ('ul. Ludwika Osieckiego'),
       ('ul. Ludwika Pasteura'),
       ('ul. Ludwika Rydygiera'),
       ('ul. Ludwika Solskiego'),
       ('ul. Ludwika Zamenhofa'),
       ('ul. Ludwinowska'),
       ('ul. Ludwisarzy'),
       ('ul. Ludźmierska'),
       ('ul. Łukasza Cieplińskiego'),
       ('ul. Łukasza Górnickiego'),
       ('ul. Łukasza Opalińskiego'),
       ('ul. Lusińska'),
       ('ul. Lutego Tura'),
       ('ul. Lwa Landaua'),
       ('ul. Lwowska'),
       ('ul. Macedońska'),
       ('ul. Macieja Dębskiego'),
       ('ul. Macieja Jakubowskiego'),
       ('ul. Macieja Kalenkiewicza'),
       ('ul. Macieja Miechowity'),
       ('ul. Macieja Moraczewskiego'),
       ('ul. Maciejkowa'),
       ('ul. Macierzanki'),
       ('ul. Maćka z Bogdańca'),
       ('ul. Maćkowa Góra'),
       ('ul. Mączna'),
       ('ul. Madejówka'),
       ('ul. Madera'),
       ('ul. Magazynowa'),
       ('ul. Magdaleny Samozwaniec'),
       ('ul. Magnolii'),
       ('ul. Mahatmy Gandhiego'),
       ('ul. Majora Ryszarda Nuszkiewicza'),
       ('ul. Majowa'),
       ('ul. Makowa'),
       ('ul. Maksyma Rylskiego'),
       ('ul. Maksymiliana i Aleksandra Gierymskich'),
       ('ul. Maksymiliana i Stanisława Cerchów'),
       ('ul. Maksymiliana Nowickiego'),
       ('ul. Maksymiliana Rutkowskiego'),
       ('ul. Mała'),
       ('ul. Malachitowa'),
       ('ul. Mała Góra'),
       ('ul. Malborska'),
       ('ul. Małego Księcia'),
       ('ul. Malinowa'),
       ('ul. Malownicza'),
       ('ul. Malutka'),
       ('ul. Malwowa'),
       ('ul. Mały Płaszów'),
       ('ul. Mały Rynek'),
       ('ul. Marcelego Nenckiego'),
       ('ul. Marchołta'),
       ('ul. Marcina Bielskiego'),
       ('ul. Marcina Borelowskiego-Lelewela'),
       ('ul. Marcowa'),
       ('ul. Margaretek'),
       ('ul. Marglowa'),
       ('ul. Mariana Batki'),
       ('ul. Mariana Czuchnowskiego'),
       ('ul. Mariana Domagały'),
       ('ul. Mariana Hemara'),
       ('ul. Mariana Langiewicza'),
       ('ul. Mariana Markowskiego'),
       ('ul. Mariana Raciborskiego'),
       ('ul. Mariana Smoluchowskiego'),
       ('ul. Marii Dąbrowskiej'),
       ('ul. Marii Grzegorzewskiej'),
       ('ul. Marii Jaremy'),
       ('ul. Marii Konopnickiej'),
       ('ul. Marii Kownackiej'),
       ('ul. Marii Skłodowskiej-Curie'),
       ('ul. Marka Kublińskiego'),
       ('ul. Martenowska'),
       ('ul. Marynarska'),
       ('ul. Marzanny'),
       ('ul. Masarska'),
       ('ul. Matematyków Krakowskich'),
       ('ul. Mateusza Birkuta'),
       ('ul. Matki Pauli Zofii Tajber'),
       ('ul. Maurycego Beniowskiego'),
       ('ul. Maurycego Mochnackiego'),
       ('ul. Mazowiecka'),
       ('ul. Mazurska'),
       ('ul. Medalionów'),
       ('ul. Medyczna'),
       ('ul. Merkuriusza Polskiego'),
       ('ul. Metalowców'),
       ('ul. Miarowa'),
       ('ul. Michała Bałuckiego'),
       ('ul. Michała Drzymały'),
       ('ul. Michała Hutnika'),
       ('ul. Michała i Stanisława Jaglarzów'),
       ('ul. Michała Korpala'),
       ('ul. Michała Ossowskiego'),
       ('ul. Michała Siedleckiego'),
       ('ul. Michała Stachowicza'),
       ('ul. Miechowska'),
       ('ul. Mieczników'),
       ('ul. Mieczykowa'),
       ('ul. Mieczysława Kamberskiego'),
       ('ul. Mieczysława Kaplickiego'),
       ('ul. Mieczysława Karłowicza'),
       ('ul. Mieczysława Medweckiego'),
       ('ul. Mieczysława Niedziałkowskiego'),
       ('ul. Mieczysława Pszona'),
       ('ul. Miedziana'),
       ('ul. Miejscowa'),
       ('ul. Mierniczych'),
       ('ul. Mierzeja Wiślana'),
       ('ul. Mieszczańska'),
       ('ul. Mieszka I'),
       ('ul. Miętowa'),
       ('ul. Migdałowa'),
       ('ul. Mikołaja Gerlaha'),
       ('ul. Mikołaja Jaskra'),
       ('ul. Mikołaja Kopernika'),
       ('ul. Mikołaja Reja'),
       ('ul. Mikołaja Zyblikiewicza'),
       ('ul. Mikołajska'),
       ('ul. Miła'),
       ('ul. Miodowa'),
       ('ul. Mirosława Dzielskiego'),
       ('ul. Mirosława Krzyżańskiego'),
       ('ul. Mirowska'),
       ('ul. Mirtowa'),
       ('ul. Misjonarska'),
       ('ul. Miśnieńska'),
       ('ul. Mistrzejowicka'),
       ('ul. Mlaskotów'),
       ('ul. Młodej Polski'),
       ('ul. Młodzieży'),
       ('ul. Młotków'),
       ('ul. Młynowa'),
       ('ul. Młynówka Królewska'),
       ('ul. Młyńska'),
       ('ul. Młyńska Boczna'),
       ('ul. Mochnaniec'),
       ('ul. Moczydło'),
       ('ul. Modra'),
       ('ul. Mogiłki'),
       ('ul. Mogilska'),
       ('ul. Mokra'),
       ('ul. Montelupich'),
       ('ul. Monterska'),
       ('ul. Monte Cassino'),
       ('ul. Morelowa'),
       ('ul. Morgi'),
       ('ul. Morsztynowska'),
       ('ul. Morwowa'),
       ('ul. Mosiężnicza'),
       ('ul. Mostowa'),
       ('ul. Moszyńskiego'),
       ('ul. Motyla'),
       ('ul. Mrówczana'),
       ('ul. Mrozowa'),
       ('ul. Murarska'),
       ('ul. Murowana'),
       ('ul. Muzyków'),
       ('ul. Mydlarska'),
       ('ul. Mydlnicka'),
       ('ul. Myśliwska'),
       ('ul. Naczelna'),
       ('ul. Nadbrzezie'),
       ('ul. Nadbrzeżna'),
       ('ul. Nadrzeczna'),
       ('ul. Nadwiślańska'),
       ('ul. Nadwodna'),
       ('ul. Nadzieja'),
       ('ul. Nad Baranówką'),
       ('ul. Nad Czerną'),
       ('ul. Nad Dłubnią'),
       ('ul. Nad Drwiną'),
       ('ul. Nad Fosą'),
       ('ul. Nad Potokiem'),
       ('ul. Nad Serafą'),
       ('ul. Nad Strugą'),
       ('ul. Nad Sudołem'),
       ('ul. Nad Zalewem'),
       ('ul. Nad Źródłem'),
       ('ul. Nagłowicka'),
       ('ul. Nałęczowska'),
       ('ul. Nałkowskiej'),
       ('ul. Napoleona Cybulskiego'),
       ('ul. Narciarska'),
       ('ul. Narcyzowa'),
       ('ul. Narvik'),
       ('ul. Nastrojowa'),
       ('ul. Nasza'),
       ('ul. Nawigacyjna'),
       ('ul. Nawojki'),
       ('ul. Nawojowska'),
       ('ul. Nazaretańska'),
       ('ul. Na Barciach'),
       ('ul. Na Błoniach'),
       ('ul. Na Błonie'),
       ('ul. Na Borach'),
       ('ul. Na Budzyniu'),
       ('ul. Na Chałupkach'),
       ('ul. Na Dołach'),
       ('ul. Na Górkach'),
       ('ul. Na Grabinach'),
       ('ul. Na Gródku'),
       ('ul. Na Grządkach'),
       ('ul. Na Jazkach'),
       ('ul. Na Klińcu'),
       ('ul. Na Kozłówce'),
       ('ul. Na Łąkach'),
       ('ul. Na Leszczu'),
       ('ul. Na Łuku'),
       ('ul. Na Mostkach'),
       ('ul. Na Niwach'),
       ('ul. Na Nowinach'),
       ('ul. Na Obrydki'),
       ('ul. Na Pokusie'),
       ('ul. Na Polach'),
       ('ul. Na Polankach'),
       ('ul. Na Szaniec'),
       ('ul. Na Ustroniu'),
       ('ul. Na Wiankach'),
       ('ul. Na Wierzchowinach'),
       ('ul. Na Wirach'),
       ('ul. Na Wrzosach'),
       ('ul. Na Wyrębe'),
       ('ul. Na Zakolu Wisły'),
       ('ul. Na Załęczu'),
       ('ul. Na Zboczu'),
       ('ul. Na Zielonki'),
       ('ul. Na Zjeździe'),
       ('ul. Na Zrębie'),
       ('ul. Nefrytowa'),
       ('ul. Niebieska'),
       ('ul. Niebyła'),
       ('ul. Niecała'),
       ('ul. Nieduża'),
       ('ul. Niedzicka'),
       ('ul. Niedźwiedziny'),
       ('ul. Niepokalanej Panny Marii'),
       ('ul. Niepołomska'),
       ('ul. Nieszawska'),
       ('ul. Nietoperzy'),
       ('ul. Niewielka'),
       ('ul. Niezapominajek'),
       ('ul. Nieznana'),
       ('ul. Nikifora'),
       ('ul. Niska'),
       ('ul. Niwy'),
       ('ul. Nizinna'),
       ('ul. Normandzka'),
       ('ul. Norymberska'),
       ('ul. Nowa'),
       ('ul. Nowa Górka'),
       ('ul. Nowogródzka'),
       ('ul. Nowohucka'),
       ('ul. Nowolipki'),
       ('ul. Nowosądecka'),
       ('ul. Nowotarska'),
       ('ul. Nowowiejska'),
       ('ul. Obopólna'),
       ('ul. Oboźna'),
       ('ul. Obozowa'),
       ('ul. Obrońców Helu'),
       ('ul. Obrońców Krzyża'),
       ('ul. Obrońców Modlina'),
       ('ul. Obrońców Poczty Gdańskiej'),
       ('ul. Obrońców Tobruku'),
       ('ul. Obrońców Warszawy'),
       ('ul. Obronna'),
       ('ul. Obrony Tyńca'),
       ('ul. Obwodowa'),
       ('ul. Odlewnicza'),
       ('ul. Odmętowa'),
       ('ul. Odmogile'),
       ('ul. Odona Bujwida'),
       ('ul. Odrzańska'),
       ('ul. Ofiar Dąbia'),
       ('ul. Ogłęczyzna'),
       ('ul. Ognistych Wici'),
       ('ul. Ogórkowa'),
       ('ul. Ogrodnicza'),
       ('ul. Ogrodniczek'),
       ('ul. Ogrodniki'),
       ('ul. Ogrodowa'),
       ('ul. Ojcowska'),
       ('ul. Okocimska'),
       ('ul. Okólna'),
       ('ul. Okopowa'),
       ('ul. Okrąg'),
       ('ul. Okręglik'),
       ('ul. Okrężna'),
       ('ul. Okulistów'),
       ('ul. Olchowa'),
       ('ul. Oleandry'),
       ('ul. Olimpijska'),
       ('ul. Olkuska'),
       ('ul. Olszanicka'),
       ('ul. Olszańska'),
       ('ul. Olszecka'),
       ('ul. Olsztyńska'),
       ('ul. Olszyny'),
       ('ul. Ondraszka'),
       ('ul. Opalowa'),
       ('ul. Opata Salwińskiego'),
       ('ul. Opatkowicka'),
       ('ul. Opolska'),
       ('ul. Opty'),
       ('ul. Oraczy'),
       ('ul. Orawska'),
       ('ul. Organki'),
       ('ul. Orla'),
       ('ul. Orląt Lwowskich'),
       ('ul. Orła Białego'),
       ('ul. Orleańska'),
       ('ul. Orlich Gniazd'),
       ('ul. Orna'),
       ('ul. Orszańska'),
       ('ul. Orzechowa'),
       ('ul. osiedle 2 Pułku Lotniczego'),
       ('ul. osiedle Albertyńskie'),
       ('ul. osiedle Górali'),
       ('ul. osiedle Krakowiaków'),
       ('ul. osiedle Oświecenia'),
       ('ul. osiedle Złotej Jesieni'),
       ('ul. Osiedlowa'),
       ('ul. Osikowa'),
       ('ul. Oskara Kolberga'),
       ('ul. Ossowskiego'),
       ('ul. Ostatnia'),
       ('ul. Ostrów'),
       ('ul. Ostrówka'),
       ('ul. Oświęcimska'),
       ('ul. Owocowa'),
       ('ul. Owsiana'),
       ('ul. Padniewskiego'),
       ('ul. Pagórkowa'),
       ('ul. Pajęcza'),
       ('ul. Palmowa'),
       ('ul. Pamiętna'),
       ('ul. Pana Cogito'),
       ('ul. Pana Tadeusza'),
       ('ul. Panoramiczna'),
       ('ul. Pańska'),
       ('ul. Papiernicza'),
       ('ul. Paproci'),
       ('ul. Parafialna'),
       ('ul. Parkowa'),
       ('ul. Partyzantów'),
       ('ul. pasaż Hetmański'),
       ('ul. Pasieczna'),
       ('ul. Pastelowa'),
       ('ul. Pasternik'),
       ('ul. Pasterska'),
       ('ul. Paulińska'),
       ('ul. Pawia'),
       ('ul. Pawła Jasienicy'),
       ('ul. Pawła Morawiańskiego'),
       ('ul. Pawła z Krosna'),
       ('ul. Pędzichów'),
       ('ul. Pejzażowa'),
       ('ul. Pękowicka'),
       ('ul. Perkuna'),
       ('ul. Perłowa'),
       ('ul. Petrażyckiego'),
       ('ul. Piaskowa'),
       ('ul. Piasta Kołodzieja'),
       ('ul. Piastowska'),
       ('ul. Piaszczysta'),
       ('ul. Piekarska'),
       ('ul. Piękna'),
       ('ul. Pielęgniarek'),
       ('ul. Pienińska'),
       ('ul. Pierzchówka'),
       ('ul. Pijarska'),
       ('ul. Piłkarska'),
       ('ul. Pilotów'),
       ('ul. Pińczowska'),
       ('ul. Piotra Bardowskiego'),
       ('ul. Piotra Borowego'),
       ('ul. Piotra Brzezińskiego'),
       ('ul. Piotra Kluzeka'),
       ('ul. Piotra Michałowskiego'),
       ('ul. Piotra Stachiewicza'),
       ('ul. Piotrusia Pana'),
       ('ul. Piwna'),
       ('ul. plac Dominikański'),
       ('ul. plac Generała Władysława Sikorskiego'),
       ('ul. plac Jana Matejki'),
       ('ul. Plac Juliusza Kossaka'),
       ('ul. plac Na Groblach'),
       ('ul. plac Nowy'),
       ('ul. plac Szczepański'),
       ('ul. plac Wszystkich Świętych'),
       ('ul. Planty'),
       ('ul. Planty Bieńczyckie'),
       ('ul. Planty Floriana Nowackiego'),
       ('ul. Płaska'),
       ('ul. Plastusia'),
       ('ul. Płaszowska'),
       ('ul. Plażowa'),
       ('ul. Pleszowska'),
       ('ul. Płomyczka'),
       ('ul. Płoszczyny'),
       ('ul. Pochyła'),
       ('ul. Pocieszka'),
       ('ul. Pocztowa'),
       ('ul. Podbagnie'),
       ('ul. Podbiałowa'),
       ('ul. Podbrzezie'),
       ('ul. Podchorążych'),
       ('ul. Podedworze'),
       ('ul. Podgórki'),
       ('ul. Podgórki Tynieckie'),
       ('ul. Podgórska'),
       ('ul. Podgwiezdna'),
       ('ul. Podhalańska'),
       ('ul. Podhalnie'),
       ('ul. Podkamyk'),
       ('ul. Podłącze'),
       ('ul. Podlesie'),
       ('ul. Podłęska'),
       ('ul. Podłużna'),
       ('ul. Podmiejska'),
       ('ul. Podmiłów'),
       ('ul. Podmokła'),
       ('ul. Podrzecze'),
       ('ul. Podskale'),
       ('ul. Podstawie'),
       ('ul. Podwale'),
       ('ul. Podwórkowa'),
       ('ul. Podzamcze'),
       ('ul. Pod Dębami'),
       ('ul. Pod Fortem'),
       ('ul. Pod Gajem'),
       ('ul. Pod Gwiazdami'),
       ('ul. Pod Janem'),
       ('ul. Pod Pomnikiem'),
       ('ul. Pod Sikornikiem'),
       ('ul. Pod Skałą'),
       ('ul. Pod Sowińcem'),
       ('ul. Pod Stokiem'),
       ('ul. Pod Strzechą'),
       ('ul. Pod Sulnikiem'),
       ('ul. Pod Szańcami'),
       ('ul. Pod Szwedem'),
       ('ul. Pod Wierzbami'),
       ('ul. Pogodna'),
       ('ul. Polarna'),
       ('ul. Poległych w Krzesławicach'),
       ('ul. Poleska'),
       ('ul. Półkole'),
       ('ul. Półłanki'),
       ('ul. Polna'),
       ('ul. Północna'),
       ('ul. Polnych Kwiatów'),
       ('ul. Polonijna'),
       ('ul. Pomorska'),
       ('ul. Pomykany'),
       ('ul. Poniedziałkowy Dół'),
       ('ul. Popielidów'),
       ('ul. Popielnik'),
       ('ul. Poprzeczna'),
       ('ul. Poręba'),
       ('ul. Porfirowa'),
       ('ul. Poronińska'),
       ('ul. Portowa'),
       ('ul. Port Solny'),
       ('ul. Porucznika Antoniego Stawarza'),
       ('ul. Porucznika Emira'),
       ('ul. Porucznika Halszki'),
       ('ul. Porzecze'),
       ('ul. Porzeczkowa'),
       ('ul. Poselska'),
       ('ul. Potockiego'),
       ('ul. Potoczek'),
       ('ul. Potrzask'),
       ('ul. Powały z Taczewa'),
       ('ul. Powiatowa'),
       ('ul. Powiśle'),
       ('ul. Powojowa'),
       ('ul. Powroźnicza'),
       ('ul. Powstańców'),
       ('ul. Powstańców Wielkopolskich'),
       ('ul. Powstania Listopadowego'),
       ('ul. Powstania Styczniowego'),
       ('ul. Poziomkowa'),
       ('ul. Poznańska'),
       ('ul. Prądnicka'),
       ('ul. Praska'),
       ('ul. Prochowa'),
       ('ul. Profesora Stefana Myczkowskiego'),
       ('ul. Profesora Tadeusza Seweryna'),
       ('ul. Profesora Teodora Spiczakowa'),
       ('ul. Profesor Janiny Bieniarzówny'),
       ('ul. Profesor Kazimierza Tadeusza Opałka'),
       ('ul. Profesor Wojciecha Marii Bartla'),
       ('ul. Profesor Zdzisława Czeppe'),
       ('ul. Prokocimska'),
       ('ul. Promienistych'),
       ('ul. Promienna'),
       ('ul. Promowa'),
       ('ul. Prosta'),
       ('ul. Pruska'),
       ('ul. Przebiśniegów'),
       ('ul. Przecinek'),
       ('ul. Przedwiośnie'),
       ('ul. Przegon'),
       ('ul. Przegorzalska'),
       ('ul. Przekątna'),
       ('ul. Przełazek'),
       ('ul. Przełęcz'),
       ('ul. Przełom'),
       ('ul. Przemiarki'),
       ('ul. Przemyska'),
       ('ul. Przemysława II'),
       ('ul. Przemysłowa'),
       ('ul. Przepiórcza'),
       ('ul. Przeskok'),
       ('ul. Przesmyk'),
       ('ul. Przewiewna'),
       ('ul. Przewóz'),
       ('ul. Przyjemna'),
       ('ul. Przykopy'),
       ('ul. Przylasek'),
       ('ul. Przylaszczki'),
       ('ul. Przymiarki'),
       ('ul. Przyrodnicza'),
       ('ul. Przyszłości'),
       ('ul. Przy Cegielni'),
       ('ul. Przy Kuźni'),
       ('ul. Przy Młynówce'),
       ('ul. Przy Moście'),
       ('ul. Przy Rondzie'),
       ('ul. Przy Torze'),
       ('ul. Pszczelna'),
       ('ul. Pszenna'),
       ('ul. Ptasia'),
       ('ul. Pułkownika Barty'),
       ('ul. Pułkownika Edwarda Gardy-Godlewskiego'),
       ('ul. Pułkownika Francesco Nullo'),
       ('ul. Pułkownika Józefa Spychalskiego'),
       ('ul. Pułkownika Stanisława Dąbka'),
       ('ul. Pustelnia'),
       ('ul. Pustynna'),
       ('ul. Puszczyków'),
       ('ul. Puszkarska'),
       ('ul. Pychowicka'),
       ('ul. Pylna'),
       ('ul. Pysocice'),
       ('ul. Pysońce'),
       ('ul. Rabczańska'),
       ('ul. Rabsztyńska'),
       ('ul. Raciborska'),
       ('ul. Racławicka'),
       ('ul. Rączna'),
       ('ul. Radłowa'),
       ('ul. Radomska'),
       ('ul. Radosna'),
       ('ul. Radzikowskiego'),
       ('ul. Radziwiłłowska'),
       ('ul. Rafała Czerwiakowskiego'),
       ('ul. Rajska'),
       ('ul. Rakowicka'),
       ('ul. Rakuś'),
       ('ul. Ratajska'),
       ('ul. Rdzawa'),
       ('ul. Redemptorystów'),
       ('ul. Reduta'),
       ('ul. Rędzina'),
       ('ul. Reformacka'),
       ('ul. Rękawka'),
       ('ul. Republiki Korczakowskiej'),
       ('ul. Retoryka'),
       ('ul. Reymonta'),
       ('ul. REZEDOWA'),
       ('ul. Roberta Jahody'),
       ('ul. Robotnicza'),
       ('ul. Rodzinna'),
       ('ul. Rodziny Jędów'),
       ('ul. Rogatka'),
       ('ul. Rokitniańska'),
       ('ul. Rolna'),
       ('ul. Rolnicza'),
       ('ul. Romana Dmowskiego'),
       ('ul. Romana Florera'),
       ('ul. Romana Ingardena'),
       ('ul. Romana Kiełkowskiego'),
       ('ul. Romana Prawocheńskiego'),
       ('ul. Rondo Czyżyńskie'),
       ('ul. Rondo Generała Maczka'),
       ('ul. rondo Grunwaldzkie'),
       ('ul. rondo Grzegórzeckie'),
       ('ul. rondo Hipokratesa'),
       ('ul. rondo Kocmyrzowskie'),
       ('ul. rondo Matecznego'),
       ('ul. rondo Mogilskie'),
       ('ul. Rondo Ofiar Katynia'),
       ('ul. Rondo Polsad'),
       ('ul. rondo Stanisława Barei'),
       ('ul. Rosista'),
       ('ul. Rotmistrza Zbigniewa Dunin-Wąsowicza'),
       ('ul. Równa'),
       ('ul. Rozalii Celakówny'),
       ('ul. Różana'),
       ('ul. Rozdroże'),
       ('ul. Rozmarynowa'),
       ('ul. Rozrywka'),
       ('ul. Ruciana'),
       ('ul. Ruczaj'),
       ('ul. Rudni'),
       ('ul. Rumiankowa'),
       ('ul. Rusałek'),
       ('ul. Rusiecka'),
       ('ul. Rusznikarska'),
       ('ul. Rusznikarska-Deptak'),
       ('ul. Rybaki'),
       ('ul. Rybałtowska'),
       ('ul. Rybianka'),
       ('ul. Rybna'),
       ('ul. Rycerska'),
       ('ul. Rymanowska'),
       ('ul. Rymarska'),
       ('ul. rynek Dębnicki'),
       ('ul. Rynek Fałęcki'),
       ('ul. Rynek Główny'),
       ('ul. rynek Kleparski'),
       ('ul. rynek Podgórski'),
       ('ul. Rysi Stok'),
       ('ul. Ryszarda Berwińskiego'),
       ('ul. Rytownicza'),
       ('ul. Rżącka'),
       ('ul. Rzeczna'),
       ('ul. Rzemieślnicza'),
       ('ul. Rzepakowa'),
       ('ul. Rzepichy'),
       ('ul. Rzeszowska'),
       ('ul. Rzeźnicza'),
       ('ul. Sadka'),
       ('ul. Sądowa'),
       ('ul. Sadzawki'),
       ('ul. Sajakówka'),
       ('ul. Salezjańska'),
       ('ul. Salwatorska'),
       ('ul. Samorządowa'),
       ('ul. Samuela Bogumiła Lindego'),
       ('ul. Sanatoryjna'),
       ('ul. Sandomierska'),
       ('ul. Sandora Petöfiego'),
       ('ul. Sanocka'),
       ('ul. Saperów'),
       ('ul. Sarmacka'),
       ('ul. Sarnie Uroczysko'),
       ('ul. Sasanek'),
       ('ul. Saska'),
       ('ul. Sebastiana Klonowica'),
       ('ul. Semperitowców'),
       ('ul. Senacka'),
       ('ul. Senatorska'),
       ('ul. Seniorów Lotnictwa'),
       ('ul. Serbska'),
       ('ul. Sergiusza Piaseckiego'),
       ('ul. Sewera'),
       ('ul. Seweryna Goszczyńskiego'),
       ('ul. Siarczanogórska'),
       ('ul. Siarczki'),
       ('ul. Sidzińska'),
       ('ul. Siejówka'),
       ('ul. Sielska'),
       ('ul. Siemomysła'),
       ('ul. Sienna'),
       ('ul. Sierpowa'),
       ('ul. Siewna'),
       ('ul. Sikorki'),
       ('ul. Siostry Faustyny'),
       ('ul. Siostry Zygmunty Zimmer'),
       ('ul. Siostrzana'),
       ('ul. Sitowiny'),
       ('ul. Siwka'),
       ('ul. Skałeczna'),
       ('ul. Skalica'),
       ('ul. Skalna'),
       ('ul. Skarbowa'),
       ('ul. Skawińska'),
       ('ul. Skibowa'),
       ('ul. Składowa'),
       ('ul. Skołczanka'),
       ('ul. Skośna'),
       ('ul. Skotnica'),
       ('ul. Skotnicka'),
       ('ul. Skowronia'),
       ('ul. Skrajna'),
       ('ul. Skręcona'),
       ('ul. Skromna'),
       ('ul. Skrzatów'),
       ('ul. Skrzyszów'),
       ('ul. Skwerowa'),
       ('ul. skwer II Korpusu Polskich Sił Zbrojnych na Zachodzie'),
       ('ul. skwer Pamięci Polaków Poszkodowanych przez III Rzeszę'),
       ('ul. Sławkowska'),
       ('ul. Sławomira Odrzywolskiego'),
       ('ul. Słoneczna'),
       ('ul. Słowiańska'),
       ('ul. Smętna'),
       ('ul. Smocza'),
       ('ul. Smolarzy'),
       ('ul. Smoleńsk'),
       ('ul. Smolki'),
       ('ul. Smolna'),
       ('ul. Snozy'),
       ('ul. Snycerska'),
       ('ul. Soboniowicka'),
       ('ul. Sobótka'),
       ('ul. Soczyny'),
       ('ul. Sodowa'),
       ('ul. Sokola'),
       ('ul. Sokolska'),
       ('ul. Solarzy'),
       ('ul. Solna'),
       ('ul. Solówki'),
       ('ul. Sołtysa Dytmara'),
       ('ul. Sołtysowska'),
       ('ul. Soroki'),
       ('ul. Sosnowa'),
       ('ul. Sosnowiecka'),
       ('ul. Sowia'),
       ('ul. Spacerowa'),
       ('ul. Spadochroniarzy'),
       ('ul. Spiska'),
       ('ul. Spiżowa'),
       ('ul. Spławy'),
       ('ul. Spokojna'),
       ('ul. Spółdzielców'),
       ('ul. Sporna'),
       ('ul. Sportowa'),
       ('ul. Spytka z Melsztyna'),
       ('ul. Srebrnych Orłów'),
       ('ul. Stacyjna'),
       ('ul. Stadionowa'),
       ('ul. Stalowa'),
       ('ul. Stańczyka'),
       ('ul. Stanisława Augusta Poniatowskiego'),
       ('ul. Stanisława Balickiego'),
       ('ul. Stanisława Brzozowskiego'),
       ('ul. Stanisława Ciechanowskiego'),
       ('ul. Stanisława Dębickiego'),
       ('ul. Stanisława Dubois'),
       ('ul. Stanisława Działowskiego'),
       ('ul. Stanisława Fiszera'),
       ('ul. Stanisława Gołąba'),
       ('ul. Stanisława Grochowiaka'),
       ('ul. Stanisława Grzepskiego'),
       ('ul. Stanisława Jachowicza'),
       ('ul. Stanisława Jasiukowicza'),
       ('ul. Stanisława Kasznicy'),
       ('ul. Stanisława Klimeckiego'),
       ('ul. Stanisława Kłosowskiego'),
       ('ul. Stanisława Konarskiego'),
       ('ul. Stanisława Kunickiego'),
       ('ul. Stanisława Lentza'),
       ('ul. Stanisława Mierzwy'),
       ('ul. Stanisława Mikołajczyka'),
       ('ul. Stanisława Mitery'),
       ('ul. Stanisława Moniuszki'),
       ('ul. Stanisława Okonia'),
       ('ul. Stanisława Pigonia'),
       ('ul. Stanisława Pronia'),
       ('ul. Stanisława Przybyszewskiego'),
       ('ul. Stanisława Pyjasa'),
       ('ul. Stanisława Rokosza'),
       ('ul. Stanisława Rostworowskiego'),
       ('ul. Stanisława Samostrzelnika'),
       ('ul. Stanisława Skarbińskiego'),
       ('ul. Stanisława Skarżyńskiego'),
       ('ul. Stanisława Staszica'),
       ('ul. Stanisława Stojałowskiego'),
       ('ul. Stanisława ze Skalbmierza'),
       ('ul. Starego Dębu'),
       ('ul. Starego Wiarusa'),
       ('ul. Stare Wiślisko'),
       ('ul. Staromostowa'),
       ('ul. Starowiejska'),
       ('ul. Starowiślna'),
       ('ul. Starowolska'),
       ('ul. Startowa'),
       ('ul. Stary Gościniec'),
       ('ul. Stawisko'),
       ('ul. Stawowa'),
       ('ul. Stefana Banacha'),
       ('ul. Stefana Batorego'),
       ('ul. Stefana Czarnieckiego'),
       ('ul. Stefana Garczyńskiego'),
       ('ul. Stefana Jaracza'),
       ('ul. Stefana Kisielewskiego'),
       ('ul. Stefana Kołaczkowskiego'),
       ('ul. Stefana Okrzei'),
       ('ul. Stefana Otwinowskiego'),
       ('ul. Stefana Rogozińskiego'),
       ('ul. Stefana Starzyńskiego'),
       ('ul. Stefana Stolarza'),
       ('ul. Stefanii Sempołowskiej'),
       ('ul. Stelmachów'),
       ('ul. Stepowa'),
       ('ul. Stoczniowców'),
       ('ul. Stoigniewa'),
       ('ul. Stokowa'),
       ('ul. Stokrotek'),
       ('ul. Stolarska'),
       ('ul. Storczykowa'),
       ('ul. Stradomska'),
       ('ul. Straszewskiego'),
       ('ul. Strażacka'),
       ('ul. Strumienna'),
       ('ul. Sucha'),
       ('ul. Świętego Jacka'),
       ('ul. Świętego Jana'),
       ('ul. Świętego Krzyża'),
       ('ul. Świętego Marka'),
       ('ul. Świętego Sebastiana'),
       ('ul. Świętego Tomasza'),
       ('ul. Świętego Wawrzyńca'),
       ('ul. Świętej Agnieszki'),
       ('ul. Świętej Anny'),
       ('ul. Świętej Gertrudy'),
       ('ul. Świętej Katarzyny'),
       ('ul. Świętej Teresy'),
       ('ul. Szara'),
       ('ul. Szczepana Humberta'),
       ('ul. Szczepańska'),
       ('ul. Szeroka'),
       ('ul. Szewska'),
       ('ul. Szlak'),
       ('ul. Szparagowa'),
       ('ul. Szpitalna'),
       ('ul. Szymona Czechowicza'),
       ('ul. Szymona Marycjusza'),
       ('ul. Szymona Zimorowicza'),
       ('ul. Tadeusza Banachiewicza'),
       ('ul. Tadeusza Czackiego'),
       ('ul. Tadeusza Hollendra'),
       ('ul. Tadeusza Kantora'),
       ('ul. Tadeusza Kasprzyckiego'),
       ('ul. Tadeusza Kochmańskiego'),
       ('ul. Tadeusza Kościuszki'),
       ('ul. Tadeusza Lehra-Spławińskiego'),
       ('ul. Tadeusza Makowskiego'),
       ('ul. Tadeusza Micińskiego'),
       ('ul. Tadeusza Motarskiego'),
       ('ul. Tadeusza Pawlikowskiego'),
       ('ul. Tadeusza Peipera'),
       ('ul. Tadeusza Połomskiego'),
       ('ul. Tadeusza Ptaszyckiego'),
       ('ul. Tadeusza Rejtana'),
       ('ul. Tadeusza Rogalskiego'),
       ('ul. Tadeusza Romanowicza'),
       ('ul. Tadeusza Sobesto'),
       ('ul. Tadeusza Starca'),
       ('ul. Tadeusza Wyrwy-Furgalskiego'),
       ('ul. Targowa'),
       ('ul. Tarłowska'),
       ('ul. Teodora Parnickiego'),
       ('ul. Teodora Rygiera'),
       ('ul. Teofila Lenartowicza'),
       ('ul. Tomasza Arciszewskiego'),
       ('ul. Tomasza Janiszewskiego'),
       ('ul. Tomasza Prylińskiego'),
       ('ul. Topolowa'),
       ('ul. Turniejowa'),
       ('ul. Twardowskiego'),
       ('ul. Tyniecka'),
       ('ul. Tytusa Czyżewskiego'),
       ('ul. Ujastek Mogilski'),
       ('ul. Ulica Luborzycka'),
       ('ul. Ulica Nierówna'),
       ('ul. Ulica Siarczana'),
       ('ul. Vlastimila Hofmana'),
       ('ul. Wacława Berenta'),
       ('ul. Wacława Gąsiorowskiego'),
       ('ul. Wacława Króla'),
       ('ul. Wacława Lipińskiego'),
       ('ul. Wacława Nałkowskiego'),
       ('ul. Wacława Popławskiego'),
       ('ul. Wacława Sieroszewskiego'),
       ('ul. Walentego Florkowskiego'),
       ('ul. Walerego Gadomskiego'),
       ('ul. Walerego Goetla'),
       ('ul. Walerego Sławka'),
       ('ul. Warszauera'),
       ('ul. Warszawska'),
       ('ul. Westerplatte'),
       ('ul. Wielopole'),
       ('ul. Wiktora Heltmana'),
       ('ul. Wilhelma Feldmana'),
       ('ul. Wilhelma i Jana Ripperów'),
       ('ul. Willowa'),
       ('ul. Wincentego Kadłubka'),
       ('ul. Wincentego Kirchmajera'),
       ('ul. Wincentego Oszustowskiego'),
       ('ul. Wincentego Pola'),
       ('ul. Wiślisko'),
       ('ul. Wiślna'),
       ('ul. Witolda Budryka'),
       ('ul. Witolda Doroszewskiego'),
       ('ul. Witolda Gombrowicza'),
       ('ul. Witolda Pileckiego'),
       ('ul. Władysława Anczyca'),
       ('ul. Władysława Bełzy'),
       ('ul. Władysława Broniewskiego'),
       ('ul. Władysława Czaplickiego'),
       ('ul. Władysława Ekielskiego'),
       ('ul. Władysława Jakubca'),
       ('ul. Władysława Jarockiego'),
       ('ul. Władysława Jaworskiego'),
       ('ul. Władysława Krygowskiego'),
       ('ul. Władysława Łokietka'),
       ('ul. Władysława Mitkowskiego'),
       ('ul. Władysława Natansona'),
       ('ul. Władysława Orkana'),
       ('ul. Władysława Podkowińskiego'),
       ('ul. Władysława Poturalskiego'),
       ('ul. Władysława Pytlasińskiego'),
       ('ul. Władysława Raczkiewicza'),
       ('ul. Władysława Rożena-Jaksy'),
       ('ul. Władysława Skoczylasa'),
       ('ul. Władysława Spasowskiego'),
       ('ul. Włodzimierza Gruszczyńskiego'),
       ('ul. Włodzimierza Puchalskiego'),
       ('ul. Włodzimierza Tetmajera'),
       ('ul. Wojciecha Bogusławskiego'),
       ('ul. Wojciecha Darasza'),
       ('ul. Wojciecha Gersona'),
       ('ul. Wojciecha Halczyna'),
       ('ul. Wojciecha Korfantego'),
       ('ul. Wojciecha Lipowskiego'),
       ('ul. Wojciecha Stattlera'),
       ('ul. Wrocławska'),
       ('ul. Wygoda'),
       ('ul. Wygrana'),
       ('ul. Xawerego Dunikowskiego'),
       ('ul. Zachodnia'),
       ('ul. Zacisze'),
       ('ul. Zakamycze'),
       ('ul. Zakopiańska'),
       ('ul. Zarzecze'),
       ('ul. Zbigniewa Herberta'),
       ('ul. Zbigniewa i Andrzeja Pronaszków'),
       ('ul. Zbigniewa Małka'),
       ('ul. Zbigniewa Seiferta'),
       ('ul. Zdzisława Jachimeckiego'),
       ('ul. Zdzisława Opiala'),
       ('ul. Zdzisława Przebindowskiego'),
       ('ul. Zenona Klemensiewicza'),
       ('ul. Zielona Droga'),
       ('ul. Zofii Kulinowskiej'),
       ('ul. Żułowska'),
       ('ul. Zwierzyniecka'),
       ('ul. Zygmunta Glogera'),
       ('ul. Zygmunta Miłkowskiego'),
       ('ul. Zygmunta Młynarskiego'),
       ('ul. Zygmunta Mysłakowskiego'),
       ('ul. Zygmunta Radnickiego'),
       ('ul. Żywiczna');